// ------------------------------------------------------------------------------
// <auto-generated>
//     VSTO host item initialization. Visual Studio may regenerate this file.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace UnassignedTicket.OutlookAddIn
{
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObject(0)]
    partial class ThisAddIn : Microsoft.Office.Tools.Outlook.OutlookAddInBase
    {
        private Microsoft.Office.Tools.CustomTaskPaneCollection _customTaskPanes;

        [System.Diagnostics.DebuggerNonUserCode]
        public ThisAddIn(
            Microsoft.Office.Tools.Outlook.ApplicationFactory factory,
            System.IServiceProvider serviceProvider)
            : base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
            Globals.Factory = factory;
        }

        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Microsoft.Office.Interop.Outlook.Application Application { get; private set; }

        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Microsoft.Office.Tools.CustomTaskPaneCollection CustomTaskPanes
        {
            get { return _customTaskPanes; }
        }

        [System.Diagnostics.DebuggerNonUserCode]
        protected override void Initialize()
        {
            base.Initialize();
            Application = GetHostItem<Microsoft.Office.Interop.Outlook.Application>(
                typeof(Microsoft.Office.Interop.Outlook.Application), "Application");
            Globals.ThisAddIn = this;
            System.Windows.Forms.Application.EnableVisualStyles();
            InitializeCachedData();
            InitializeControls();
            InitializeComponents();
            InitializeData();
        }

        [System.Diagnostics.DebuggerNonUserCode]
        protected override void FinishInitialization()
        {
            InternalStartup();
            OnStartup();
        }

        [System.Diagnostics.DebuggerNonUserCode]
        protected override void InitializeData()
        {
            BeginInitialization();
            BindToData();
            EndInitialization();
        }

        [System.Diagnostics.DebuggerNonUserCode]
        protected override void InitializeControls()
        {
            _customTaskPanes = Globals.Factory.CreateCustomTaskPaneCollection(
                null, null, "CustomTaskPanes", "CustomTaskPanes", this);
        }

        [System.Diagnostics.DebuggerNonUserCode]
        protected override void InitializeComponents()
        {
        }

        [System.Diagnostics.DebuggerNonUserCode]
        protected override void InitializeCachedData()
        {
        }

        [System.Diagnostics.DebuggerNonUserCode]
        private void BindToData()
        {
        }

        [System.Diagnostics.DebuggerNonUserCode]
        private void StartCaching(string memberName)
        {
        }

        [System.Diagnostics.DebuggerNonUserCode]
        private void StopCaching(string memberName)
        {
        }

        [System.Diagnostics.DebuggerNonUserCode]
        private bool IsCached(string memberName)
        {
            return false;
        }

        [System.Diagnostics.DebuggerNonUserCode]
        private void BeginInitialization()
        {
            BeginInit();
            _customTaskPanes.BeginInit();
        }

        [System.Diagnostics.DebuggerNonUserCode]
        private void EndInitialization()
        {
            _customTaskPanes.EndInit();
            EndInit();
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Applications.Hosting", "17.0")]
    internal sealed partial class Globals
    {
        private static ThisAddIn _thisAddIn;
        private static Microsoft.Office.Tools.Outlook.ApplicationFactory _factory;

        private Globals()
        {
        }

        internal static ThisAddIn ThisAddIn
        {
            get { return _thisAddIn; }
            set
            {
                if (_thisAddIn == null)
                {
                    _thisAddIn = value;
                }
                else
                {
                    throw new System.NotSupportedException();
                }
            }
        }

        internal static Microsoft.Office.Tools.Outlook.ApplicationFactory Factory
        {
            get { return _factory; }
            set
            {
                if (_factory == null)
                {
                    _factory = value;
                }
                else
                {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
